---
# ## Role: docker
# # Docker config, this is just converted directly to json in /etc/docker/daemon.json
# docker_config:
#   ipv6: false
#   icc: true
#   userland-proxy: true
#   no-new-privileges: false
#   experimental: true
#   selinux-enabled: false
#   dns: []
run_docker_role: true # if false or unset the role doesn't run
# ## End role: docker
