---
# Packages
apt_packages:
  - bat
  - build-essential
  - ca-certificates
  - curl
  - direnv
  - dnsutils
  - git
  - gnupg
  - htop
  - iproute2
  - iptables
  - iputils-ping
  - jq
  - libcairo2-dev
  - libcurl4-openssl-dev
  - libffi-dev
  - libreadline-dev
  - libpcsclite-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxslt1-dev
  - libyaml-dev
  - pass
  - pkg-config
  - python3
  - python3-pip
  - python3-venv
  - python3-dev
  - ripgrep
  - software-properties-common
  - sqlite3
  - stow
  - sudo
  - tldr
  - tmux
  - wget
  - zlib1g-dev
  - zsh
