# Packages
apt_packages:
  - bat
  - build-essential
  - bison
  - ca-certificates
  - cron
  - cron-daemon-common
  - curl
  - direnv
  - dnsutils
  - gettext
  - git
  - gnupg
  - htop
  - interception-caps2esc
  - iproute2
  - iptables
  - iputils-ping
  - jq
  - kitty-terminfo
  - libcairo2-dev
  - libcurl4-openssl-dev
  - libevent-dev
  - libffi-dev
  - libpcsclite-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxslt1-dev
  - libyaml-dev
  - zlib1g-dev
  - libfindbin-libs-perl
  - make
  - ncurses-dev
  - openssl
  - openssh-client
  - openssh-server
  - ssh-askpass
  - pass
  - pkg-config
  - python3
  - python3-dev
  - python3-pip
  - python3-venv
  - rustc
  - ripgrep
  - software-properties-common
  - sqlite3
  - stow
  - sudo
  - tealdeer
  - tmux
  - trash-cli
  - unzip
  - wget
  - yacc
  - zlib1g-dev
  - zsh
# Installed by another package manager
apt_packages_uninstall:
  - bat
  - direnv
  - gnupg
  - yq
  - ripgrep
  - tealdeer
  - glow
  - neovim
