---
galaxy_info:
  author: mfaine
  role_name: mise
  description: Configures mise (package manager)
  company: NaTS
  license: GPLv3
  min_ansible_version: "2.13"
  platforms:
    - name: Ubuntu
      versions:
        - "25.04"
  galaxy_tags: ['Package Managers']
