---
- name: Create zim_home directory
  ansible.builtin.file:
    path: "{{ target_home_path }}/.zim"
    state: directory
  become: true
  become_user: '{{ target_username }}'

- name: Download zimfw
  ansible.builtin.command: >
    curl -fsSL -o "$ZIM_HOME/zimfw.zsh" "{{ zimfw_download_url }}"
  environment:
    ZIM_HOME: "{{ target_home_path }}/.zim"
  become: true
  become_user: '{{ target_username }}'
