---
galaxy_info:
  author: mfaine
  role_name: doppler
  description: Configures doppler (secrets manager)
  company: NaTS
  license: GPLv3
  min_ansible_version: "2.13"
  platforms:
    - name: Ubuntu
      versions:
        - "25.04"
  galaxy_tags: ['Secrets Managers']
