---
# Packages
apt_packages:
  - build-essential
  - ca-certificates
  - curl
  - cron
  - cron-daemon-common
  - dnsutils
  - gettext
  - htop
  - iproute2
  - iptables
  - iputils-ping
  - jq
  - libcurl4-openssl-dev
  - libffi-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxslt1-dev
  - libyaml-dev
  - software-properties-common
  - sqlite3
  - stow
  - sudo
  - tldr
  - wget
  - zlib1g-dev
  - zsh

# Installed by asdf
apt_packages_uninstall:
  - bat
  - direnv
  - gnupg
  - yq
  - ripgrep
  - tldr
  - glow
  - neovim
