---
# Packages
apt_packages:
  - ca-certificates
  - curl
  - wget
  - stow
  - zsh
  - direnv
  - jq
  - tmux
  - ripgrep
  - git
  - zlib1g-dev
  - build-essential
  - libssl-dev
  - libreadline-dev
  - libyaml-dev
  - libsqlite3-dev
  - sqlite3
  - libxml2-dev
  - libxslt1-dev
  - libcurl4-openssl-dev
  - pass
  - software-properties-common
  - sudo
  - stow
  - libffi-dev
  - python3
  - python3-pip
  - python3-venv
  - iproute2
  - iptables
  - iputils-ping
  - dnsutils
